name: aymontage_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_fonts: ^1.1.0
  sign_button: ^0.0.6
  google_nav_bar: ^3.0.0
  line_icons: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter  


flutter:

  uses-material-design: true

  assets:
    - images/loggedOut_page.jpg
    - images/post1_example.jpg
    - images/post2_example.jpg
    - images/post3_example.jpg
    - images/post4_example.jpg
    - images/post5_example.jpg
